site_name: "citydb-3dtiler"
repo_url: "https://github.com/tum-gis/citydb-3dtiler"
site_url: "https://tum-gis.github.io/citydb-3dtiler"
#edit_uri: "tree/main/docs"
# exclude_docs: |
#   /html_documents/
#   /notebooks/
nav:
  - Home: index.md
  - "How to use?": how_to_use.md
  - "Tips for Docker usage" : tips_for_docker_usage.md
  - "Documentation for Developers" : developer_docs.md
  - "To-Do list" : to-do_list.md
theme: material
extra_css:
  - extra_style.css
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
